# Generated by Django 2.1.5 on 2019-04-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_address_billing_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
    ]
