# Generated by Django 2.1.5 on 2019-04-22 15:39

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_remove_address_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
