# Generated by Django 2.1.5 on 2019-04-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_remove_address_address_type'),
    ]
