# Generated by Django 2.1.5 on 2019-04-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.TextField(blank=True, help_text='Contact phone number'),
        ),
    ]
