# Generated by Django 2.1.5 on 2019-04-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0006_auto_20190422_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=12),
        ),
    ]
