# Generated by Django 2.1.5 on 2019-04-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0007_auto_20190422_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
