# Generated by Django 2.1.5 on 2019-04-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190422_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', related_name='shipping_address', to='addresses.Address'),
        ),
    ]
