# Generated by Django 2.1.5 on 2019-04-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190422_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address_final',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
