# Generated by Django 2.1.5 on 2019-09-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20190731_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Shipped', 'Shipped'), ('Paid', 'Paid'), ('Delivered', 'Delivered')], default='created', max_length=120),
        ),
    ]
